### ISSUE TITLE
Invalid length for parameter StandardsSubscriptionRequests

### ISSUE THREAD

**Issue by LewisYates** [awslabs/aws-securityhub-multiaccount-scripts#37]
Getting the following error when executing the codebuild job to enable multiple accounts:

Full Output: 
Traceback (most recent call last):
  File "enablesecurityhub.py", line 351, in <module>
sh_client.batch_enable_standards(StandardsSubscriptionRequests=batch_enable_standards_input)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 599, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 647, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter StandardsSubscriptionRequests, value: 0, valid range: 1-inf

**Comment by avishayil** [comment]
I'm experiencing this issue as well

**Comment by ssteo** [comment]
Sncountered the same issue as well, should be fixed in this PR https://github.com/awslabs/aws-securityhub-multiaccount-scripts/pull/40
